[package]
name = "xrt-cuda"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
cuda = ["dep:cudarc"]

[dependencies]
cudarc = { workspace = true, optional = true, features = ["driver", "nvrtc", "cublas", "f16", "cuda-12000"] }
half.workspace = true
tracing.workspace = true
xrt-core = { path = "../xrt-core" }
xrt-gguf = { path = "../xrt-gguf" }
xrt-kernels = { path = "../xrt-kernels" }

[[example]]
name = "compile_ptx"
required-features = ["cuda"]
