[package]
name = "xrt-models"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
cuda = ["xrt-cuda/cuda"]
moe-route-trace = []
moe-router-exact-reference = []

[dependencies]
bytemuck.workspace = true
half.workspace = true
parking_lot.workspace = true
serde_json.workspace = true
tracing.workspace = true
xrt-core = { path = "../xrt-core" }
xrt-cuda = { path = "../xrt-cuda" }
xrt-gguf = { path = "../xrt-gguf" }
xrt-kernels = { path = "../xrt-kernels" }
xrt-safetensors = { path = "../xrt-safetensors" }
