[package]
name = "xrt-cli"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
cuda = ["xrt-runtime/cuda"]

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
xrt-hub = { path = "../xrt-hub" }
xrt-openai = { path = "../xrt-openai" }
xrt-runtime = { path = "../xrt-runtime" }
xrt-tokenizer = { path = "../xrt-tokenizer" }
